version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /app
    volumes:
      - ./:/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
